name: bachu
description: Bachu
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  firebase_core: ^2.7.0
  get: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in:
  location: ^4.4.0
  intl: ^0.18.0
  geolocator: ^9.0.2
  flutter_geocoder: ^0.2.2-nullsafety
  font_awesome_flutter:
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
      - family: Anurati
        fonts:
          - asset: assets/fonts/Anurati-Regular.otf
      - family: e-Ukraine
        fonts:
          - asset: assets/fonts/e-Ukraine-Regular.otf
            weight: 400
          - asset: assets/fonts/e-Ukraine-Medium.otf
            weight: 500
          - asset: assets/fonts/e-Ukraine-Bold.otf
            weight: 700
      - family: Keania
        fonts:
          - asset: assets/fonts/KeaniaOne-Regular.ttf