name: bachu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  location: ^4.4.0
  intl: ^0.18.0
  geolocator: ^9.0.2
  flutter_geocoder: ^0.2.2-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
