name: bachu
description: Bachu
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  get:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
